name = 'store'
type = 'javascript'

workers_dev = true
compatibility_date = "2022-02-16"
main = "./dist/worker.js"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
