name: Deploy Checkout Pages

on:
  push:
    branches:
      - main
  # push:
  #   paths:
  #     - deployments/checkout/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ^6

      - name: Install Dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm check -F checkout

      - name: Build
        run: pnpm build -F checkout

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./deployments/checkout
          command: pages publish --project-name=checkout-mfe out
